# Generated by Django 3.2.9 on 2021-12-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('message', models.TextField(blank=True, verbose_name='متن کامنت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('artilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.article')),
            ],
        ),
    ]
