# Generated by Django 3.2.9 on 2021-12-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comments_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
